### ISSUE TITLE
Allow dismissing alerts without a full page reload

### ISSUE THREAD

**Issue by milancermak** [crytic/amarna#41]
So I'm not sure this is something you can actually do anything about, but if you can, that would be great.

[Here's an example of a PR that's full of Amarna alerts](https://github.com/BibliothecaForAdventurers/realms-contracts/pull/139/files#diff-cbc41607957f00442320e6d07ac71cd806e98e6206da5613cde42fca3d43f24e). A lot of them are false positives in the context of the PR - the "potential for overflows" is not really a problem when we're multiplying small numbers that are (more or less) under our control.

So during the PR review, I want to go through each alert and dismiss the alert:

<img width="605" alt="Screenshot 2022-06-24 at 21 18 25" src="https://user-images.githubusercontent.com/184055/175650872-47d0dcaa-22fb-496c-a1ac-376658ab11d8.png">

However, when I click the Dismiss alert button, a full page reload happens which takes a couple of seconds and I'm then yanked out of the context, because the page doesn't even load back to the file and line I was reviewing (where I dismissed the alert). 

Ideally, I would want the alert dismissal to happen "inline," silently, without a full page refresh, so I can continue with the review. Is that something you can control or is it a GitHub thing?

**Comment by coolhill** [comment]
It does sounds like something that would be under Github control since it is a part of their code scanning feature. However there are multiple ways to manage/dismiss findings as described in the [docs](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository). For example if you want to dismiss multiple warnings simultaneously you could do it thru `Security->Code Scanning alerts`. Alternatively during review `Ctrl-click` the `Show more details` and close it in the new tab.
